/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyspa;

import imagenfondo.ImagenFondo;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;


/**
 *
 * @author Daniel
 */
public class frmSpa extends javax.swing.JFrame {

    TareasBD tareasBD;
    /**
     * Creates new form frmSpa
     */
    public frmSpa() {
        setTitle("UltraTone Beauty");
        initComponents();
        tareasBD=new TareasBD();
        //tareasBD.Conectar();
        //setIconImage(new ImageIcon(getClass().getResource("../recursos/iconoAplicacion1.png")).getImage());
        //escritorio.setBorder(new ImagenFondo());
        this.setExtendedState(frmSpa.MAXIMIZED_BOTH);
    }
    
    //int cont=1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBarSpa = new javax.swing.JMenuBar();
        menuA = new javax.swing.JMenu();
        mitemVActividad = new javax.swing.JMenuItem();
        mitemNActividad = new javax.swing.JMenuItem();
        mitemEActividad = new javax.swing.JMenuItem();
        mitemELActividad = new javax.swing.JMenuItem();
        menuP = new javax.swing.JMenu();
        mitemNProcedimiento = new javax.swing.JMenuItem();
        mitemEProcedimiento = new javax.swing.JMenuItem();
        mitemCProcedimiento = new javax.swing.JMenuItem();
        mitemELProcedimiento = new javax.swing.JMenuItem();
        menuRG = new javax.swing.JMenu();
        mitemNRG = new javax.swing.JMenuItem();
        mitemERG = new javax.swing.JMenuItem();
        mitemCRC = new javax.swing.JMenuItem();
        mitemELRG = new javax.swing.JMenuItem();
        menuF = new javax.swing.JMenu();
        mitemIF = new javax.swing.JMenuItem();
        mitemIC = new javax.swing.JMenuItem();
        menuC = new javax.swing.JMenu();
        mitemDC = new javax.swing.JMenuItem();
        mitemCLimpiar = new javax.swing.JMenuItem();
        mitemConectar = new javax.swing.JMenuItem();
        mitemDesconectarBD = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmSpa"); // NOI18N
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        menuA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1382914993_calendar.png"))); // NOI18N
        menuA.setText("Agenda");

        mitemVActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/date.png"))); // NOI18N
        mitemVActividad.setText("Ver actividades");
        mitemVActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemVActividadActionPerformed(evt);
            }
        });
        menuA.add(mitemVActividad);

        mitemNActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/date_add.png"))); // NOI18N
        mitemNActividad.setText("Nueva actividad");
        mitemNActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemNActividadActionPerformed(evt);
            }
        });
        menuA.add(mitemNActividad);

        mitemEActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/date_edit.png"))); // NOI18N
        mitemEActividad.setText("Editar actividad");
        mitemEActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemEActividadActionPerformed(evt);
            }
        });
        menuA.add(mitemEActividad);

        mitemELActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/date_delete.png"))); // NOI18N
        mitemELActividad.setText("Eliminar actividad");
        mitemELActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemELActividadActionPerformed(evt);
            }
        });
        menuA.add(mitemELActividad);

        menuBarSpa.add(menuA);

        menuP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/database.png"))); // NOI18N
        menuP.setText("Procedimientos");

        mitemNProcedimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/database_add.png"))); // NOI18N
        mitemNProcedimiento.setText("Nuevo");
        mitemNProcedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemNProcedimientoActionPerformed(evt);
            }
        });
        menuP.add(mitemNProcedimiento);

        mitemEProcedimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/database_edit.png"))); // NOI18N
        mitemEProcedimiento.setText("Editar");
        mitemEProcedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemEProcedimientoActionPerformed(evt);
            }
        });
        menuP.add(mitemEProcedimiento);

        mitemCProcedimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/database_go.png"))); // NOI18N
        mitemCProcedimiento.setText("Consultar");
        mitemCProcedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemCProcedimientoActionPerformed(evt);
            }
        });
        menuP.add(mitemCProcedimiento);

        mitemELProcedimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/database_delete.png"))); // NOI18N
        mitemELProcedimiento.setText("Eliminar");
        mitemELProcedimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemELProcedimientoActionPerformed(evt);
            }
        });
        menuP.add(mitemELProcedimiento);

        menuBarSpa.add(menuP);

        menuRG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1382914990_user.png"))); // NOI18N
        menuRG.setText("Registro de Clientes");

        mitemNRG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/group_add.png"))); // NOI18N
        mitemNRG.setText("Nuevo");
        mitemNRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemNRGActionPerformed(evt);
            }
        });
        menuRG.add(mitemNRG);

        mitemERG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/group_edit.png"))); // NOI18N
        mitemERG.setText("Editar");
        mitemERG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemERGActionPerformed(evt);
            }
        });
        menuRG.add(mitemERG);

        mitemCRC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/group_go.png"))); // NOI18N
        mitemCRC.setText("Consultar");
        mitemCRC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemCRCActionPerformed(evt);
            }
        });
        menuRG.add(mitemCRC);

        mitemELRG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/group_delete.png"))); // NOI18N
        mitemELRG.setText("Eliminar");
        mitemELRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemELRGActionPerformed(evt);
            }
        });
        menuRG.add(mitemELRG);

        menuBarSpa.add(menuRG);

        menuF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1382915062_file.png"))); // NOI18N
        menuF.setText("Informes");

        mitemIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/page_add.png"))); // NOI18N
        mitemIF.setText("Factura");
        mitemIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemIFActionPerformed(evt);
            }
        });
        menuF.add(mitemIF);

        mitemIC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/group.png"))); // NOI18N
        mitemIC.setText("Clientes");
        mitemIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemICActionPerformed(evt);
            }
        });
        menuF.add(mitemIC);

        menuBarSpa.add(menuF);

        menuC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cog.png"))); // NOI18N
        menuC.setText("Configuración");

        mitemDC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/color_wheel.png"))); // NOI18N
        mitemDC.setText("Diseño");
        mitemDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemDCActionPerformed(evt);
            }
        });
        menuC.add(mitemDC);

        mitemCLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/layout_delete.png"))); // NOI18N
        mitemCLimpiar.setText("Limpiar escritorio");
        mitemCLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemCLimpiarActionPerformed(evt);
            }
        });
        menuC.add(mitemCLimpiar);

        mitemConectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/connect.png"))); // NOI18N
        mitemConectar.setText("Conectar BD");
        mitemConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemConectarActionPerformed(evt);
            }
        });
        menuC.add(mitemConectar);

        mitemDesconectarBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/disconnect.png"))); // NOI18N
        mitemDesconectarBD.setText("Desconectar BD");
        mitemDesconectarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemDesconectarBDActionPerformed(evt);
            }
        });
        menuC.add(mitemDesconectarBD);

        menuBarSpa.add(menuC);

        setJMenuBar(menuBarSpa);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitemNProcedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemNProcedimientoActionPerformed
        ifrmNProcedimiento obj=new ifrmNProcedimiento(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
        //obj.setTitle("Procediemiento"/*+cont*/);
    }//GEN-LAST:event_mitemNProcedimientoActionPerformed

    private void mitemIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemIFActionPerformed
        ifrmGFactura obj=new ifrmGFactura(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemIFActionPerformed

    private void mitemDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemDCActionPerformed
        ifrmConfiguracionDiseño obj=new ifrmConfiguracionDiseño();
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemDCActionPerformed

    private void mitemNRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemNRGActionPerformed
        ifrmNCliente obj=new ifrmNCliente(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemNRGActionPerformed

    private void mitemNActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemNActividadActionPerformed
        ifrmNActividad obj=new ifrmNActividad(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemNActividadActionPerformed

    private void mitemCProcedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemCProcedimientoActionPerformed
        ifrmCProcedimiento obj=new ifrmCProcedimiento(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemCProcedimientoActionPerformed

    private void mitemVActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemVActividadActionPerformed
        ifrmVerActividad obj=new ifrmVerActividad(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemVActividadActionPerformed

    private void mitemEActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemEActividadActionPerformed
        ifrmEActividad obj=new ifrmEActividad(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemEActividadActionPerformed

    private void mitemELActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemELActividadActionPerformed
        ifrmELAcitividad obj=new ifrmELAcitividad(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemELActividadActionPerformed

    private void mitemEProcedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemEProcedimientoActionPerformed
        ifrmEProcedimiento obj=new ifrmEProcedimiento(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemEProcedimientoActionPerformed

    private void mitemELProcedimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemELProcedimientoActionPerformed
        ifrmELProcedimiento obj=new ifrmELProcedimiento(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemELProcedimientoActionPerformed

    private void mitemERGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemERGActionPerformed
        ifrmECliente obj=new ifrmECliente(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemERGActionPerformed

    private void mitemCRCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemCRCActionPerformed
        ifrmCCliente obj=new ifrmCCliente(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemCRCActionPerformed

    private void mitemELRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemELRGActionPerformed
        ifrmELCliente obj=new ifrmELCliente(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemELRGActionPerformed

    private void mitemCLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemCLimpiarActionPerformed
        this.escritorio.removeAll();
        this.escritorio.repaint();
    }//GEN-LAST:event_mitemCLimpiarActionPerformed

    private void mitemDesconectarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemDesconectarBDActionPerformed
        tareasBD.cierraConexion();
    }//GEN-LAST:event_mitemDesconectarBDActionPerformed

    private void mitemConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemConectarActionPerformed
        tareasBD.Conectar();
    }//GEN-LAST:event_mitemConectarActionPerformed

    private void mitemICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemICActionPerformed
        ifrmGCliente obj=new ifrmGCliente(this, true, tareasBD);
        escritorio.add(obj);
        obj.show();
    }//GEN-LAST:event_mitemICActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSpa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSpa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu menuA;
    private javax.swing.JMenuBar menuBarSpa;
    private javax.swing.JMenu menuC;
    private javax.swing.JMenu menuF;
    private javax.swing.JMenu menuP;
    private javax.swing.JMenu menuRG;
    private javax.swing.JMenuItem mitemCLimpiar;
    private javax.swing.JMenuItem mitemCProcedimiento;
    private javax.swing.JMenuItem mitemCRC;
    private javax.swing.JMenuItem mitemConectar;
    private javax.swing.JMenuItem mitemDC;
    private javax.swing.JMenuItem mitemDesconectarBD;
    private javax.swing.JMenuItem mitemEActividad;
    private javax.swing.JMenuItem mitemELActividad;
    private javax.swing.JMenuItem mitemELProcedimiento;
    private javax.swing.JMenuItem mitemELRG;
    private javax.swing.JMenuItem mitemEProcedimiento;
    private javax.swing.JMenuItem mitemERG;
    private javax.swing.JMenuItem mitemIC;
    private javax.swing.JMenuItem mitemIF;
    private javax.swing.JMenuItem mitemNActividad;
    private javax.swing.JMenuItem mitemNProcedimiento;
    private javax.swing.JMenuItem mitemNRG;
    private javax.swing.JMenuItem mitemVActividad;
    // End of variables declaration//GEN-END:variables
}
