/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyspa;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Daniel
 */
public class ifrmEActividad extends javax.swing.JInternalFrame {

    DefaultTableModel modelo;
    TareasBD tareasBaseDatos;
    /**
     * Creates new form ifrmEActividad
     */
    public ifrmEActividad(java.awt.Frame parent, boolean modal, TareasBD tareasBaseDatos) {
        initComponents();
        //super(parent, modal);
        this.tareasBaseDatos=tareasBaseDatos;
        modelo=(DefaultTableModel)(jTable1.getModel());
        tareasBaseDatos.listar("select *from Agenda", modelo);
        btnBuscarHora.setEnabled(false);
        txtCedula.setEnabled(false);
        txtCod_pro.setEnabled(false);
        txtHora.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCod_pro = new javax.swing.JTextField();
        btnBuscarHora = new javax.swing.JButton();
        btnVerTodos = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Editar Actividad");

        jLabel1.setText("Fecha:");

        jLabel2.setText("Hora:");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Cédula:");

        jLabel8.setText("Código Procedimiento:");

        btnBuscarHora.setText("Buscar");
        btnBuscarHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHoraActionPerformed(evt);
            }
        });

        btnVerTodos.setText("Ver todos");
        btnVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscarHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(btnVerTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCod_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCod_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(btnVerTodos)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarHora))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(34, 34, 34)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date date = jDateChooser1.getDate(); 
        SimpleDateFormat format2=new SimpleDateFormat("dd/MM/yyyy"); 
        String fecha = format2.format(date);
        tareasBaseDatos.listar("select *from Agenda where fecha_A='"+fecha+"'", modelo);
        btnBuscarHora.setEnabled(true);
        txtHora.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHoraActionPerformed
        String hora=txtHora.getText();
        
        if (btnBuscarHora.getText().equals("Buscar")){
            System.out.println("buscar");
            Agenda obj=new Agenda();
            Date date = jDateChooser1.getDate(); 
            SimpleDateFormat format2=new SimpleDateFormat("dd/MM/yyyy"); 
            String fecha = format2.format(date);
            System.out.println(fecha);
            obj.setFecha_A(fecha);
            System.out.println(hora);
            obj.setHora_A(hora);
            if (tareasBaseDatos.consultarActividad(obj)){
                jDateChooser1.setDate(date);
                jDateChooser1.enable();
                txtHora.setText(""+obj.getHora_A());
                txtHora.setEnabled(true);
                txtCedula.setText(obj.getCedula());
                txtCod_pro.setText(obj.getCod_pro());
                System.out.println(txtCedula.getText()+"\n"+txtCod_pro.getText());
                
                btnVerTodos.setEnabled(false);
                jButton1.setEnabled(false);
                btnBuscarHora.setText("Guardar");
                
                txtCedula.setEnabled(true);
                txtCod_pro.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(null, "Hora invalida", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            System.out.println("modificar");
            Agenda obj=new Agenda();
            Date date = jDateChooser1.getDate(); 
            SimpleDateFormat format2=new SimpleDateFormat("dd/MM/yyyy"); 
            String fecha = format2.format(date);
            System.out.println(fecha);
            obj.setFecha_A(fecha);
            System.out.println(txtHora.getText());
            obj.setHora_A(txtHora.getText());
            obj.setCedula(txtCedula.getText());
            obj.setCod_pro(txtCod_pro.getText());
            System.out.println(txtCedula.getText()+"\n"+txtCod_pro.getText());
            
            if (tareasBaseDatos.modificarActividad(obj)){
                JOptionPane.showMessageDialog(null, "Los datos han sido modificados", "OK", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Error al modificar", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            
            limpiar();
            btnBuscarHora.setText("Modificar");
            txtCedula.setEnabled(false);
            txtCod_pro.setEnabled(false);
            btnVerTodos.setEnabled(true);
            jButton1.setEnabled(true);
            jDateChooser1.disable();
            txtHora.setEnabled(false);
            System.out.println(txtCedula.getText()+"\n"+txtCod_pro.getText());
            
            tareasBaseDatos.listar("select *from Agenda", modelo);
        }
    }//GEN-LAST:event_btnBuscarHoraActionPerformed

    private void btnVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodosActionPerformed
        tareasBaseDatos.listar("select *from Agenda", modelo);
        txtCedula.setEnabled(false);
        txtCod_pro.setEnabled(false);
    }//GEN-LAST:event_btnVerTodosActionPerformed

    public void limpiar(){
        txtCedula.setText("");
        txtCod_pro.setText("");
        txtHora.setText("");
        jDateChooser1.setDate(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarHora;
    private javax.swing.JButton btnVerTodos;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCod_pro;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
